### PR TITLE
Unify attachment api

### LINKED ISSUE #33: Unify attachment handling API
Currently we have the following function signatures for adding attachments to an Email struct:
```
func (email *Email) AddAttachment(file string, name ...string) *Email
func (email *Email) AddAttachmentBase64(b64File, name string) *Email
func (email *Email) AddAttachmentData(data []byte, filename, mimeType string) *Email
func (email *Email) AddInline(file string, name ...string) *Email
func (email *Email) AddInlineBase64(b64File, name, mimeType string) *Email
func (email *Email) AddInlineData(data []byte, filename, mimeType string) *Email
```
For some reason `AddAttachment` and `AddInline`  are variadic but only accept one name:
```
        if len(name) > 1 {
                email.Error = errors.New("Mail Error: Attach can only have a file and an optional name")
                return email
        }
```
Other functions take `name` as parameter and possibly also `mimeType`.

I propose we modify all these functions to accept `name` and `mimeType`. So the API would become:
```
func (email *Email) AddAttachment(file, name, mimeType string) *Email
func (email *Email) AddAttachmentBase64(b64Data, name, mimeType string) *Email
func (email *Email) AddAttachmentData(data []byte, name, mimeType string) *Email
func (email *Email) AddInline(file, name, mimeType string) *Email
func (email *Email) AddInlineBase64(b64Data, name, mimeType string) *Email
func (email *Email) AddInlineData(data []byte, name, mimeType string) *Email
```

edit. I changed argument name `b64File` -> `b64Data` so it is consistent with `file` and `data` arguments.

### PR DESCRIPTION
**Pull request by xhit**
Merge all attachment to only one `Email` method called `Attach` and use the struct `File` to set the attachment information.

Fix #33

### CODE REVIEW

File: attach.go [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+// You can define if attachment is inline or not.
+type File struct {
+	// FilePath is the path of the file to attach.
+	FilePath string
+	// Name is the name of file in attachment. Required for Data and B64File. Optional for FilePath.
+	Name string
+	// MimeType of attachment. If empty then is obtained from Name (if not empty) or FilePath. If cannot obtained, application/octet-stream is set.
+	MimeType string
+	// B64File is the base64 string of file to attach.
+	B64File string
```
Comment (jlinnosa) [inline attach.go:22]: I think this could be `B64Data` as it relates more to the `Data` field than `FilePath` field (or the former `file` argument)...

File: attach.go [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+func getAttachmentType(file *File) (attachType, error) {
+	// 1- data
+	// 2- base64
+	// 3- file
+
+	// first check if Data
+	if len(file.Data) > 0 {
+		// data requires a name
+		if len(file.Name) == 0 {
+			return 0, errors.New("Mail Error: Attach from bytes requires a name")
```
Comment (jlinnosa) [inline attach.go:90]: I think you can drop the `Mail Error: ` preamble from this error string as you append it on the upper level also.

File: attach.go [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+		}
+		return attachData, nil
```
Comment (jlinnosa) [inline attach.go:92]: Is it ok to have multiple data fields populated or should it be an error condition if more than one of `FilePath`, `B64File` and `Data` contain data?

File: attach.go (hunk 1 above)
Comment (xhit) [reply attach.go:22]: Yes, B64Data is better. But Data refers to []byte in this case. Maybe B64String?

File: attach.go (hunk 2 above)
Comment (xhit) [reply attach.go:90]: Thanks for catch this. I will correct it.

File: attach.go (hunk 3 above)
Comment (xhit) [reply attach.go:92]: Yes, it's ok to have multiple, but only will be use one and is selected in this order:

- `Data`
- `B64File`
- `FilePath`

So, if `FilePath` and `B64File` is set, this last is used and `FilePath` is ignored.

Maybe a doc is need it in the struct.

File: attach.go (hunk 1 above)
Comment (jlinnosa) [reply attach.go:22]: Could be, but I think of it more from the perspective of the meaning of the name than the underlying data structure. Both `Data` and `B64Data` would contain the _actual_ attachment data and `FilePath` has only the name of the location of the actual data.

It is semantics and not terribly important to the actual implementation, but to my ear it sounds better to have `Data` in both field names.

File: attach.go (hunk 3 above)
Comment (jlinnosa) [reply attach.go:92]: Yes. It is a good idea to document the precedence order.

I am a bit worried about the possibility that the implementation will silently skip erroneous input. This could mask a bug in the application using this library.

File: attach.go (hunk 1 above)
Comment (xhit) [reply attach.go:22]: >  I think of it more from the perspective of the meaning of the name than the underlying data structure

I got it.

File: attach.go (hunk 3 above)
Comment (xhit) [reply attach.go:92]: This implementation is used a lot in aws-sdk-go. For example, to index an image to rekognition, you can use bytes or S3 Object image https://github.com/aws/aws-sdk-go/blob/v1.38.27/service/rekognition/api.go#L11972-L11982

I don't know if return an error when use multiple or use an order, but I don't think the package can skip erroneous input because the `getAttachmentType` function can handle this. Any "silent error" is a bad implementation of developer.

I will document the precedence order. And left this conversation open some days. If we find a bug I will update. Any check let me know.

Comment (xhit) [reply attach.go:94]: I decide close this conversation because is not a breaking change and developers, at any problem, can use the old way instead.

**Comment by xhit** [comment]
This PR is completed. I will left opened for reviews until [Cinco de Mayo](https://en.wikipedia.org/wiki/Cinco_de_Mayo)

**Comment by jlinnosa** [comment]
What I meant by the "shim" was a simple layer to translate old API into new.
e.g.
```
func (email *Email) AddInline(file, name, mimeType string) *Email {
        return email.Attach(&File{FilePath: file, Name: name, MimeType: mimeType, Inline: true})
}
```
This way you don't have to have duplicate implementations and the old tests should pass.

**Comment by xhit** [comment]
Done.
